
import * as LucideIcons from 'lucide-react';

// Re-export all icons with the Icon suffix to avoid conflicts
export const {
  Loader2: Loader2Icon,
  Mail: MailIcon,
  Lock: LockIcon,
  User: UserIcon,
  ExternalLink: ExternalLinkIcon,
  MapPin: MapPinIcon,
  CalendarDays: CalendarDaysIcon,
  Clock: ClockIcon,
  Heart: HeartIcon,
  Plus: PlusIcon,
  Share2: Share2Icon,
  Ticket: TicketIcon,
  Star: StarIcon,
  Users: UsersIcon,
  TrendingUp: TrendingUpIcon,
  PartyPopper: PartyPopperIcon,
  Music: MusicIcon,
  Palette: PaletteIcon,
  Trophy: TrophyIcon,
  Utensils: UtensilsIcon,
  Calendar: CalendarIcon,
  Check: CheckIcon,
  Info: InfoIcon,
  Sparkles: SparklesIcon,
  PlusCircle: PlusCircleIcon,
  Trash2: Trash2Icon,
  Edit: EditIcon,
  AlertCircle: AlertCircleIcon,
  LogOut: LogOutIcon,
  X: XIcon,
  Send: SendIcon,
  Bot: BotIcon,
  ChevronUp: ChevronUpIcon,
  ChevronDown: ChevronDownIcon,
  Car: CarIcon,
  Navigation: NavigationIcon,
  Filter: FilterIcon,
  Locate: LocateIcon,
  Search: SearchIcon,
  Moon: MoonIcon,
  Sun: SunIcon,
  Satellite: SatelliteIcon,
  Map: MapIcon,
  Compass: CompassIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  DollarSign: DollarSignIcon,
  Settings: SettingsIcon
} = LucideIcons;
