
project_id = "akwvmljopucsnorvdwuu"
[functions.search-events-simple]
enabled = true
verify_jwt = true
import_map = "./functions/search-events-simple/deno.json"
entrypoint = "./functions/search-events-simple/index.ts"
